import Menu from "./menu";
import Head from "next/head";
import Link from "next/link";
function Layout({ children, metaTitle, description, titlePage }) {
	return (
		<div>
			<Head>
				<title>{metaTitle}</title>
				<meta
					name={description}
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav>
				<div className="container mx-auto">
					<div className="flex flex-wrap justify-between px-4 my-4">
						<div className="w-1/4">
							<Link href="/">
								<a>
									<h3>Logo Brand</h3>
								</a>
							</Link>
						</div>

						<div className="menu w-8/12 flex justify-end">
							<Menu />
						</div>
					</div>
				</div>
			</nav>

			<header>
				<div className="container mx-auto">
					<div className="flex flex-wrap px-4">
						<div className="w-full text-center bg-blue-50 h-52 flex items-center justify-center">
							<h1 className="text-4xl text-slate-600 capitalize">
								{titlePage}
							</h1>
						</div>
					</div>
				</div>
			</header>

			{children}

			<footer className="mt-8">
				<div className="container mx-auto">
					<div className="flex flex-wrap px-4">
						<div className="w-full mx-auto text-center bg-blue-100 py-4">
							<strong>Footer</strong>
						</div>
					</div>
				</div>
			</footer>
		</div>
	);
}

Layout.defaultProps = {
	title: "Blog Page NextJs",
	description: "Description by default",
};

export default Layout;
